apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  externalTrafficPolicy: Local 