name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        Write-Host "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env | Invoke-Expression

    - name: Check for required files
      shell: powershell
      run: |
        Write-Host "Checking for required files in app/client directory..."
        Get-ChildItem -Path "${{ github.workspace }}/app/client" -Force
        
        # Check for Dockerfile
        if (-not (Test-Path "${{ github.workspace }}/app/client/Dockerfile")) {
          Write-Host "Dockerfile not found, creating it..."
          Set-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "FROM node:18-alpine as build"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "WORKDIR /app"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "COPY package*.json ./"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "RUN npm install --legacy-peer-deps"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "COPY . ."
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "ENV PUBLIC_URL="
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "RUN npm run build"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "RUN ls -la /app/build"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "FROM nginx:alpine"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "COPY --from=build /app/build /usr/share/nginx/html"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "RUN rm /etc/nginx/conf.d/default.conf"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "COPY nginx.conf /etc/nginx/conf.d/default.conf"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value "EXPOSE 80"
          Add-Content -Path "${{ github.workspace }}/app/client/Dockerfile" -Value 'CMD ["nginx", "-g", "daemon off;"]'
          Write-Host "Dockerfile created successfully"
        } else {
          Write-Host "Dockerfile found!"
          Get-Content "${{ github.workspace }}/app/client/Dockerfile"
        }
        
        # Check for nginx.conf
        if (-not (Test-Path "${{ github.workspace }}/app/client/nginx.conf")) {
          Write-Host "nginx.conf not found, creating it..."
          Set-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "server {"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    listen 80;"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value ""
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    location / {"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "        root /usr/share/nginx/html;"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "        index index.html index.htm;"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value '        try_files $uri $uri/ /index.html;'
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    }"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value ""
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    error_page 500 502 503 504 /50x.html;"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    location = /50x.html {"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "        root /usr/share/nginx/html;"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "    }"
          Add-Content -Path "${{ github.workspace }}/app/client/nginx.conf" -Value "}"
          Write-Host "nginx.conf created successfully"
        } else {
          Write-Host "nginx.conf found!"
          Get-Content "${{ github.workspace }}/app/client/nginx.conf"
        }

    - name: Build Docker image
      shell: powershell
      run: |
        Write-Host "Current directory contents:"
        Get-ChildItem -Path "${{ github.workspace }}/app/client"
        
        # Create a basic package.json file for the build
        Write-Host "Creating package.json file..."
        Set-Content -Path "${{ github.workspace }}/app/client/package.json" -Value "{" 
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "name": "ecommerce-app",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "version": "1.0.0",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "private": true,'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "dependencies": {'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "react": "^18.2.0",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "react-dom": "^18.2.0",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "react-scripts": "5.0.1",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "ajv": "^8.12.0",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "ajv-keywords": "^5.1.0"'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  },'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "scripts": {'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "start": "react-scripts start",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "build": "react-scripts build",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "test": "react-scripts test",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "eject": "react-scripts eject"'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  },'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  "browserslist": ['
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    ">0.2%",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "not dead",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "not ie <= 11",'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '    "not op_mini all"'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '  ]'
        Add-Content -Path "${{ github.workspace }}/app/client/package.json" -Value '}'
        
        # Create a basic index.html file for the build
        Write-Host "Creating index.html file..."
        New-Item -Path "${{ github.workspace }}/app/client/public" -ItemType Directory -Force
        Set-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '<!DOCTYPE html>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '<html lang="en">'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '<head>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '  <meta charset="utf-8" />'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '  <meta name="viewport" content="width=device-width, initial-scale=1" />'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '  <title>E-Commerce App</title>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '</head>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '<body>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '  <div id="root">'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '    <h1>E-Commerce App</h1>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '    <p>Welcome to our online store!</p>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '  </div>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '</body>'
        Add-Content -Path "${{ github.workspace }}/app/client/public/index.html" -Value '</html>'
        
        # Create a basic React app structure
        Write-Host "Creating React app files..."
        New-Item -Path "${{ github.workspace }}/app/client/src" -ItemType Directory -Force
        Set-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value 'import React from "react";'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value 'import ReactDOM from "react-dom/client";'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value 'import App from "./App";'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value ''
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value 'const root = ReactDOM.createRoot(document.getElementById("root"));'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value 'root.render('
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value '  <React.StrictMode>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value '    <App />'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value '  </React.StrictMode>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/index.js" -Value ');'
        
        Set-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value 'import React from "react";'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value ''
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value 'function App() {'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '  return ('
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '    <div className="App">'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '      <header className="App-header">'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '        <h1>E-Commerce App</h1>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '        <p>Welcome to our online store!</p>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '      </header>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '    </div>'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '  );'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value '}'
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value ''
        Add-Content -Path "${{ github.workspace }}/app/client/src/App.js" -Value 'export default App;'
        
        Set-Location -Path "${{ github.workspace }}/app/client"
        Write-Host "Building Docker image from $(Get-Location)"
        docker build -t i222401/ecommerce:latest .

    - name: Login to Docker Hub
      shell: powershell
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      shell: powershell
      run: |
        docker push i222401/ecommerce:latest

    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f ${{ github.workspace }}/deployment.yaml
        kubectl apply -f ${{ github.workspace }}/service.yaml

    - name: Verify deployment
      shell: powershell
      run: |
        Write-Host "Waiting for deployment to be ready..."
        kubectl rollout status deployment/ecommerce-app
        Write-Host "Service details:"
        kubectl get service ecommerce-service

    - name: Get application URL
      shell: powershell
      run: |
        Write-Host "Application URL:"
        minikube service ecommerce-service --url
