name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        Write-Host "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env | Invoke-Expression

    - name: Build Docker image
      shell: powershell
      working-directory: ./app/client
      run: |
        docker build -t i222401/ecommerce:latest .

    - name: Login to Docker Hub
      shell: powershell
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      shell: powershell
      run: |
        docker push i222401/ecommerce:latest

    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify deployment
      shell: powershell
      run: |
        Write-Host "Waiting for deployment to be ready..."
        kubectl rollout status deployment/ecommerce-app
        Write-Host "Service details:"
        kubectl get service ecommerce-service

    - name: Get application URL
      shell: powershell
      run: |
        Write-Host "Application URL:"
        minikube service ecommerce-service --url
